cnn:
  classfication:
    # Training part parameters
    training:
      dev_sample_percentage: .1
      class_Flood_data_file: training_set/hazards/Flood/data.txt
      class_IncreaseInWaterLevel_data_file: training_set/warningsign/IncreaseInWaterLevel/data.txt
      class_Landslide_data_file: training_set/hazards/Landslide/data.txt
      class_LeaningTelephonePole_data_file: training_set/warningsign/LeaningTelephonePole/data.txt
      class_Others_data_file: training_set/Others/data.txt
      # Define model hyper-parameters
      embedding_dim: 128
      filter_sizes: 3,4,5,6
      num_filters: 128
      dropout_keep_prob: 0.5
      l2_reg_lambda: 0.0
      # Define training parameters
      batch_size: 50
      num_epochs: 200
      evaluate_every: 100
      checkpoint_every: 500
      num_checkpoints: 5
      # Define Misc Parameters
      allow_soft_placement: True
      log_device_placement: False
      vocab_dir: models
    # Predicting part parameters
    predicting:
      class_Flood_data_file: training_set/hazards/Flood/data.txt
      class_IncreaseInWaterLevel_data_file: training_set/warningsign/IncreaseInWaterLevel/data.txt
      class_Landslide_data_file: training_set/hazards/Landslide/data.txt
      class_LeaningTelephonePole_data_file: training_set/warningsign/LeaningTelephonePole/data.txt
      class_Others_data_file: training_set/Others/data.txt
      # Eval Parameters
      batch_size: 64
      # Not in using.
      checkpoint_dir:
      model_dir: models/landslipPred-1000
      vocab_dir: models
      # Define Misc Parameters
      allow_soft_placement: True
      log_device_placement: False

